### ISSUE TITLE
Signatur

### ISSUE THREAD

**Issue by mrh-line** [frittex/moneymoney-bawagpsk#2]
Ich wollte dich fragen, ob ich deine Extension auch auf https://moneymoney-app.com/extensions verlinken darf?

**Comment by frittex** [comment]
Hallo @mrh-line, ich habe dieses Issue erst jetzt entdeckt, sorry für die sehr späte Reaktion.
Ich wäre mit einer Verlinkung einverstanden, allerdings möchte ich nicht so gerne mit Klarnamen dort gelistet sein. Gibt es eine Möglichkeit, nur mit dem Github Handle verlinkt zu werden?

**Comment by mrh-line** [comment]
Klar, kein Problem. Vielen Dank. Ich habe dein Extension soeben verlinkt.

**Comment by frittex** [comment]
Hallo @mrh-line, ich habe neue Changes gepusht, um die Extension auch mit den von Bawag PSK verwendeten SMS-Codes für die PSD2 kompatibel zu machen. Könntest du die neue Version verlinken und signieren?

**Comment by frittex** [comment]
@mrh-line Ich habe gerade gesehen, dass auf der Downloadseite bereits die neue Version verlinkt ist, daher schließe ich dieses Issue. Danke für die Anpassung!
